### PR TITLE
setInterval does not fire if card is in background

### PR DESCRIPTION
**Pull request by joshthecoder**
This is a thing in webOS 3.0.2, apparently intentional, where they disable setInterval from firing. Will try swapping in a setTimeout that re-sets itself.

### CODE REVIEW

**Comment by joshthecoder** [comment]
Here's my first take at implementing Alarm based refreshes. Appears to work good so far. Only issue I have noticed that's a biggy is each refresh marks all statuses as "read". This shouldn't happen, the unread count should just go up until the user reads through them or marks all as read.

Please review and let me know areas of improvement. I left in the setInterval code, it's commented out. I imagine we need a way to configure between alarms and setInterval to support non-webOS (ex: chrome).

**Comment by joshthecoder** [comment]
Oh also the interval frequency is hard coded at the moment.
Alarms are set to fire in HH:MM:SS formatted string.  We can probably just store the interval
in minutes instead of seconds to make it simple.

**Comment by funkatron** [comment]
Let's stick with the current storage format. converting old users to the new stuff means we have to keep one-time conversion code around forever, and it's a real pain.

I don't think we should push it up past 5m anyway; gets battery drainy. 8)

I think we may need to switch to a headless startup, because if an alarm fires while the app is closed, it will re-open the app's card otherwise. You _could_ get around this as long as you cancel the existing alarm on shutdown, but I worry that might not be easy – under Mojo it was basically not possible to do this reliably, for example.

**Comment by joshthecoder** [comment]
The alarm is cancelled when the app unloads (unload method). Seems to work fine and doesn't reboot the app.
Eventually I am planning to try implementing the polling into a service (Node). Might help improve UI performance and also avoid this alarm/setinterval trouble.

**Comment by funkatron** [comment]
cool, if you're seeing decent handling with unload, let's at least go with this for now and push it out to the folks who were asking about it for testing.

**Comment by funkatron** [comment]
also, yes, a Node.js approach for grabbing and processing data makes the most sense, imho.

**Pull request merged**
